### ISSUE TITLE
Are you really using YaleB?

### ISSUE THREAD

**Issue by Kobe972** [dhingratul/FaceRecognition#1]
I remember there are 10 classes in YaleB, but your dataset has 38 classes.

**Comment by dhingratul** [comment]
Can you point out the code and line number you are referring to ?

**Comment by Kobe972** [comment]
In readme: `Implemented and evaluated four basic face recognition algorithms: Eigenfaces, Fisherfaces, Support Vector Machine (SVM), and Sparse Representation-based Classification (SRC) on YaleB dataset`. I was looking for YaleB dataset, but YaleB_32x32 contains 38 classes instead of 10 classes. I think it may be YaleB_ext?

**Comment by dhingratul** [comment]
Most likely yes.
